name: Deploy Project
# multiple event. for e.g. in following event - we can also run the workflow manually
on: [push, workflow_dispatch]
jobs:
  #job1
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v7
    - name: Install dependencies
      run: npm ci
    - name: Run Lint
      run: npm run lint
    - name: Build Code
      run: npm run build
    - name: Deploy Code
      run: echo "Deploying..."
