name: Deploy Project
# multiple event. for e.g. in following event - we can also run the workflow manually
on: [push, workflow_dispatch]
jobs:
  #job1
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    - name: Install NodeJS
      uses: actions/setup-node@v7
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint
      run: npm run lint
  #job2
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v7
    - name: Install NodeJS
      uses: actions/setup-node@v7
      with:
        node-version: 24
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
  #job3
  build: 
    # Use "needs" keyword if you want to run yur jobs sequentially
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Install NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying.."